name: "CI tests"

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  ci-tests:
    name: "tests"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/osbuild/rpmrepo-ci:latest
    steps:
    - name: "Clone Repository"
      uses: actions/checkout@v2

    # This verifies the formatting of the repository configurations in ./repo/ and
    # tries to verify external references.
    - name: "Run repo-check"
      run: |
        ./src/script/repo-check.py ./repo/*.json
        ./src/script/repo-check.py --check-external public ./repo/*.json

    - name: "Run update schutzfile tests"
      run: |
        python3 -m pytest ./.github/scripts/test_update_schutzfile.py

    - name: "Run gateway tests"
      run: python3 -m pytest src/gateway/*.py
